### ISSUE TITLE
Tbeam Board Reconigzed but instalation fails

### ISSUE THREAD

**Issue by sergionaf** [meshtastic/Meshtastic-gui-installer#222] opened 2022-06-28 18:00 UTC
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 94:b9:7e:d2:45:88
Uploading stub...
Traceback (most recent call last):
File "/Users/sergio/somedir/venv/lib/python3.10/site-packages/meshtastic_flasher/esptool_form.py", line 70, in run

esptool.main(command)
File "/Users/sergio/somedir/venv/bin/esptool.py", line 4722, in main

esp = esp.run_stub()
File "/Users/sergio/somedir/venv/bin/esptool.py", line 891, in run_stub

self.mem_block(stub[field][from_offs:to_offs], seq)
File "/Users/sergio/somedir/venv/bin/esptool.py", line 755, in mem_block

return self.check_command("write to target RAM", self.ESP_MEM_DATA,
File "/Users/sergio/somedir/venv/bin/esptool.py", line 505, in check_command

raise FatalError.WithResult('Failed to %s' % op_description, status_bytes)
esptool
.
FatalError
:
Failed to write to target RAM (result was 01070000: Operation timed out)

**Comment by garthvh** [comment] 2022-06-28 21:49
Does the tbeam have SoftRF on it?

**Comment by sergionaf** [comment] 2022-06-28 23:36
No,
I alredy upload other Lora Examples using Arduino IDE

**Comment by garthvh** [comment] 2022-06-29 02:12
You are probably going to have to use the install script for the first install, the flasher does not work reliably yet with other firmware on the device (they often are using the serial port too)

**Comment by garthvh** [comment] 2022-06-29 02:13
Dupe of #159

**Closed by garthvh** 2022-06-29 02:12 UTC
